version: '3.8'

services:
  internet-monitor:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./internet_logs:/app/internet_logs
