version: '3.8'

services:
  internet-monitor-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.vps
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Node.js Configuration
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}

      # Location name for display
      - LOCATION_NAME=${LOCATION_NAME:-Home Connection Monitor}

      # Timezone (optional)
      - TZ=${TZ:-UTC}

    volumes:
      # Bind mount to host directory where SCP uploads land
      - /opt/internet-monitor/logs:/app/logs

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Resource limits (lightweight for dashboard only)
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

# No named volumes needed - using bind mounts
